trigger:
- main

pool:
  name: 'New-pool'   # tumhara self-hosted agent pool ka naam

variables:
- group: variable group   # tumhara variable group ka naam

stages:
# -------------------- BUILD STAGE --------------------
- stage: Build
  displayName: Build & Push
  jobs:
  - job: BuildDocker
    steps:
    - script: |
        echo "Logging in to Azure with Service Principal..."
        az login --service-principal \
          --username $(AZURE_CLIENT_ID) \
          --password $(AZURE_CLIENT_SECRET) \
          --tenant $(AZURE_TENANT_ID)

        echo "Logging in to ACR..."
        az acr login -n $(ACR_NAME)

        echo "Building Docker image..."
        docker build -t $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG) .

        echo "Pushing image with build tag..."
        docker push $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG)

        echo "Tagging as latest..."
        docker tag $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG) \
          $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest
        docker push $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest
      displayName: 'Build & Push to ACR'

# -------------------- DEPLOY STAGE --------------------
- stage: Deploy
  displayName: Deploy to VM
  dependsOn: Build
  jobs:
  - job: DeployToVM
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'sshconnection'
        commands: |
          cd ~/my-node-app

          echo "Logging in to Azure with Service Principal..."
          az login --service-principal \
            --username $AZURE_CLIENT_ID \
            --password $AZURE_CLIENT_SECRET \
            --tenant $AZURE_TENANT_ID

          echo "Logging in to ACR..."
          az acr login -n $ACR_NAME

          echo "Stopping old containers for this project..."
          docker-compose down || true

          echo "Cleaning up unused images..."
          docker image prune -af || true

          echo "Pulling latest image..."
          docker-compose pull

          echo "Starting services..."
          docker-compose up -d
      env:
        AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
        AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
        AZURE_TENANT_ID: $(AZURE_TENANT_ID)
        ACR_NAME: $(ACR_NAME)
