trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'azanacr'
  acrLoginServer: 'azanacr-f7eabjd2gsczcke4.azurecr.io'
  imageName: 'nodeapp'
  tag: $(Build.BuildId)

stages:
- stage: Build
  jobs:
  - job: BuildDocker
    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: '**/Dockerfile'
        containerRegistry: 'MyDockerRegistryServiceConnection'
        tags: |
          $(tag)
          latest

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToVM
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'sshconnection'
        runOptions: inline
        inline: |
          echo "Login to ACR"
          docker login $(acrLoginServer) -u $(acrName) -p $(acrPassword)
          
          echo "Deploying app"
          export TAG=$(tag)
          cd ~/my-node-app
          docker-compose pull
          docker-compose up -d

