trigger:
- main

pool:
  name: 'New-pool'   # tumhara self-hosted agent pool ka naam

variables:
- group: variable group   # tumhara variable group ka naam

stages:
# -------------------- BUILD STAGE --------------------
- stage: Build
  displayName: Build & Push
  jobs:
    - job: BuildDocker
      steps:
        - script: |
            echo "Logging in to Azure..."
            az login --service-principal \
              --username "$AZURE_CLIENT_ID" \
              --password "$AZURE_CLIENT_SECRET" \
              --tenant "$AZURE_TENANT_ID"

            echo "Logging in to ACR..."
            az acr login -n $(ACR_NAME)

            echo "Building Docker image..."
            docker build -t $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG) .

            echo "Pushing image with build tag..."
            docker push $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG)

            echo "Tagging as latest..."
            docker tag $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG) \
                        $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest
            docker push $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest
          displayName: "Build & Push to ACR"
          env:
            AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
            AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
            AZURE_TENANT_ID: $(AZURE_TENANT_ID)


# -------------------- DEPLOY (DEBUG) --------------------
- stage: Deploy
  displayName: Deploy to VM
  dependsOn: Build
  jobs:
    - job: DeployToVM
      steps:
        - task: SSH@0
          inputs:
            sshEndpoint: 'sshconnection'
            commands: |
              echo "=== DEBUG ENV VARIABLES ON VM ==="
              echo "CLIENT_ID: $AZURE_CLIENT_ID"
              echo "TENANT_ID RAW: '$AZURE_TENANT_ID'"
              echo "TENANT_ID TRIMMED: '$(echo $AZURE_TENANT_ID | tr -d '[:space:]')'"
              echo "SECRET length: ${#AZURE_CLIENT_SECRET}"

              az login --service-principal \
                --username "$AZURE_CLIENT_ID" \
                --password "$AZURE_CLIENT_SECRET" \
                --tenant "$(echo $AZURE_TENANT_ID | tr -d '[:space:]')"

              az account show
          env:
            AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
            AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
            AZURE_TENANT_ID: $(AZURE_TENANT_ID)
