trigger:
- main

pool:
  name: 'New-pool'   # tumhara self-hosted agent pool ka naam

variables:
- group: variable group   # tumhara variable group ka naam

stages:
# -------------------- BUILD STAGE --------------------
- stage: Build
  displayName: Build & Push
  jobs:
  - job: BuildDocker
    steps:
    - script: |
        echo "Logging in to Azure with Service Principal..."
        az login --service-principal --username $(AZURE_CLIENT_ID) --password $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
        echo "Logging in to ACR..."
        az acr login -n $(ACR_NAME)

        echo "Building Docker image..."
        docker build -t $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG) .

        echo "Pushing image with build tag..."
        docker push $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG)

        echo "Tagging as latest..."
        docker tag $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG) \
          $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest
        docker push $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest
      displayName: 'Build & Push to ACR'

# -------------------- DEPLOY (DEBUG) --------------------
- stage: Deploy
  displayName: Debug Variables Only
  dependsOn: Build
  jobs:
    - job: DebugVars
      displayName: "Print pipeline variables"
      steps:
        - script: |
            echo "=== Debugging Pipeline Variables ==="

            echo "ACR_NAME = $(ACR_NAME)"
            echo "IMAGE_NAME = $(IMAGE_NAME)"
            echo "IMAGE_TAG = $(IMAGE_TAG)"

            echo "AZURE_CLIENT_ID = $(AZURE_CLIENT_ID)"      # should show ***
            echo "AZURE_TENANT_ID = $(AZURE_TENANT_ID)"      # may show masked
            echo "AZURE_CLIENT_SECRET = $(AZURE_CLIENT_SECRET)"  # will show ***

            echo "--- Checking lengths of secrets ---"
            echo "AZURE_CLIENT_ID length: ${#AZURE_CLIENT_ID}"
            echo "AZURE_CLIENT_SECRET length: ${#AZURE_CLIENT_SECRET}"
            echo "AZURE_TENANT_ID length: ${#AZURE_TENANT_ID}"
          displayName: "Print variable values (safe check)"
