trigger:
- main

pool:
  name: 'New-pool'   # <-- your self-hosted agent pool name

variables:
  acrName: 'azanacr'
  acrLoginServer: 'azanacr-f7eabjd2gsczcke4.azurecr.io'
  imageName: 'nodeapp'
  tag: $(Build.BuildId)

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: '**/Dockerfile'
        containerRegistry: 'MyDockerRegistryServiceConnection'
        tags: |
          $(tag)
          latest

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToVM
    steps:
    - script: |
        echo "Logging in to ACR..."
        docker login $(acrLoginServer) -u $(acrName) -p $(acrPassword)

        echo "Deploying app with Docker Compose..."
        export TAG=$(tag)
        cd ~/my-node-app
        docker-compose pull
        docker-compose up -d
      displayName: "Deploy Docker Compose"
